### ISSUE TITLE
Design GUI

### ISSUE THREAD

**Issue by kendallliang** [everettknudsen/BME547FinalProject#1]

**Comment by kendallliang** [comment]
Matrix location of GUI widgets

**Comment by nicwainwright** [comment]
gonna get started here on a branch 'basicGUI'. will probably not be able to do much with the GUI until more of the program is built out

**Comment by nicwainwright** [comment]
okay so, first window will be a welcome. ask for 'email'. this email will either initialize a new mongo object for this user, and proceed to upload/download options OR proceed to upload/download options for existing user

**Comment by nicwainwright** [comment]
@kendallliang soo after enter email screen, let's do another screen that gives option for either upload or download and then proceeds to next screen

@everettknudsen you mentioned we need to make sure to have back buttons... I'll be sure to keep this in mind

**Comment by nicwainwright** [comment]
okay, running into a thought process fault. @kendallliang im thinking we prolly need to implement client code inside of GUI code, for ease of use. what do you think?

**Comment by nicwainwright** [comment]
if this is the case, i need to download your server code now to start working with it

**Comment by kendallliang** [comment]
I think that makes sense--we need to the requests.post within the gui.py file then

**Comment by nicwainwright** [comment]
right now i have the window for login destroy itself and then presumably call the next gui window

**Comment by nicwainwright** [comment]
need to implement 'requests' commands inside my gui, but working on interface flow for now @kendallliang

**Comment by nicwainwright** [comment]
okay here's pseudocode structure im thinking
login -> then display main menu (upload, download, finish)
-upload
--browse files for image and select processing option
---send to server
----success message
-----return to main menu
-download
--dropdown menu for images to view
---after selecting a image, display this image on left and open a new dropdown menu with compare options to other processed versions of image
----after selecting a comparison, show metadata and histogram button and download button below image
----- download button will open a file browser to select location
----- histogram button will display a new window with histogram shown
------ once done with this window, can click menu to return to main menu
-finish (closes app)

@everettknudsen @kendallliang

**Comment by nicwainwright** [comment]
@kendallliang yo, add this to your requirements.txt 

opencv-python

pip install opencv-python is how i installed it

**Comment by nicwainwright** [comment]
maybe we need version nubmer?

**Comment by nicwainwright** [comment]
@kendallliang how far along are you on processing an image? in this same upload window, I want to display an option to change the processing of the photo from REGULAR to histogram, log, etc. i might just create the dropdown menu but worry about the actual processing later. Currently i am working with PIL to view photos. so if we can figure out processing of that file type, would be best
