### ISSUE TITLE
implement mongo with commented info

### ISSUE THREAD

**Issue by nicwainwright** [everettknudsen/BME547FinalProject#11]
timestamps, image, processedd images, previous actions and metrics

**Comment by nicwainwright** [comment]
@everettknudsen let's use a ID system as follows: if a new user, find smallest ID number that isn't used yet and assign this user ID to the new user

**Comment by nicwainwright** [comment]
wait actually let's use email

**Comment by everettknudsen** [comment]
How do we want to structure the database in terms of storing the images? Any ideas?

**Comment by everettknudsen** [comment]
We have fully determined the structure we will implement for the MongoDB. We will have a user database, then an imbedded images database. Finally, there will be a metrics dictionary associated with each image.

**Comment by nicwainwright** [comment]
wait so, whats the structure? is it like this?

usersDict = {"userEmail": imageDict}
- imageDict = {"imagename_processType": metricsDict}
-- metricsDict = {"data": imagedata_string_base64, 
                           "size": img_size_inBytes,
                           "metrics": [ (timestamp, latency_of_processing) ] }

where "metrics" key is attached to a list of tuples?

@everettknudsen @kendallliang
