### ISSUE TITLE
unit testing of image processing functions/gui

### ISSUE THREAD

**Issue by kendallliang** [everettknudsen/BME547FinalProject#24]
how are we supposed to unit test to make sure an image was processed correctly? for example, we locally attempted to do histogram equalization outside of our histEQ function and then compare that result to the result from our histEQ function. however, pytest didn't like to compare numpy arrays via assert: 
```
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

how are we supposed to ensure that the gui functions generate the correct widgets?

**Comment by dward2** [comment]
That is the right approach.  But, as the error says, you may need to write your assert like:
```
assert all(ndarray1 == ndarray2)
```
or something like that.

Alternatively, sometimes it is easier to not compare the entire image array, but just a part of it.  For example, some of my numpy arrays that have images have three dimension.  So, I might do an assert like:

```
all(ndarray1[0:20, 0, 0] = [60 23 40 25 ...])
```
where the list [60 23 40 25...] I derived by running a sample image through the function to be tested ahead of time.

Does that make sense?  If that doesn't work, let me know and point to the test you are trying and I can take a more detailed look.
