### ISSUE TITLE
Recording the timestamps of image processing

### ISSUE THREAD

**Issue by nicwainwright** [everettknudsen/BME547FinalProject#28]
@dward2 quick question. since I have the option of changing between compression/processing options BEFORE uploading, do I take the time stamp of every time I run a process (histogram, contrast, etc) even though only one version will be uploaded? Or do I only save the latency and timestamp of the final type of processing I choose before uploading?

**Comment by nicwainwright** [comment]
i am uploading a screen recording to google drive right now to show you what I mean with narration

**Comment by nicwainwright** [comment]
https://drive.google.com/file/d/18aLZ2MNuP6q5qNlaNa-n_7GZCY0LVDHQ/view?usp=sharing

use this link to access my screen recording on my google drive

**Comment by dward2** [comment]
Lets go with just storing the info for when you upload the image.  Yes, your server is doing some processing steps each time you click one of the buttons.  But, if it is only storing the final choice, just record the timestamp and latency for the final upload.

**Comment by nicwainwright** [comment]
got it thanks
